
[functions.post-scheduler]
enabled = true
verify_jwt = true
import_map = "./functions/post-scheduler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/post-scheduler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/post-scheduler/*.html" ]

[functions.generate-youtube-auth-url]
enabled = true
verify_jwt = true
import_map = "./functions/generate-youtube-auth-url/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-youtube-auth-url/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-youtube-auth-url/*.html" ]
